import java.awt.Graphics2D;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DamageDecorator.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//


public abstract class DamageDecorator extends RoboFighter {
	RoboFighter decoratedRoboFigher; 
	
	public DamageDecorator(RoboFighter roboFighter) {
		super(roboFighter);
		this.decoratedRoboFigher = roboFighter;
		//decoratedRoboFigher.sync(this);
	}
	
	@Override
	public void step(double deltaTime) {
		this.strategy.move(this, deltaTime);
		decoratedRoboFigher.sync(this);
	}
	
	
	@Override
	public void sync(RoboFighter r) {
		x = r.x;
		y = r.y;
		ammunition = r.ammunition;
		damage = r.damage;
		indStrength = r.indStrength;
		radius = r.radius;
		decoratedRoboFigher.sync(this);
	}
}
