import java.awt.Color;
import java.awt.Graphics2D;
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entity.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//




public abstract class Entity {
	public double x;
	public double y;
	public int radius;
	public Simulation simulation;
	public boolean isActive;
	public Color color;
	
	public void step(double deltaTime) {
	
	}
	
	public Entity(int radius, Simulation simulation) {
		this.simulation = simulation;
		this.isActive = true;
		this.radius = radius;
		
		x = simulation.randomGenerator.nextInt(simulation.zoneWidth - 2*radius - 1) + radius + 1;
		y = simulation.randomGenerator.nextInt(simulation.zoneHeight - 2*radius - 1) + radius + 1;
		
		while(FightStrategy.insideCheck(x, y, simulation.legend.width, simulation.legend.height, -1*radius) > 0) {
			x = simulation.randomGenerator.nextInt(simulation.zoneWidth - 2*radius - 1) + radius + 1;
			y = simulation.randomGenerator.nextInt(simulation.zoneHeight - 2*radius - 1) + radius + 1;
		}
		
	}
	
	//@Override
	public void draw(Graphics2D g2d) {
		g2d.setColor(this.color);
		g2d.drawOval((int) x - radius,(int) y - radius, (int) 2*radius, (int) 2*radius); 
	}

}
