import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediumDamaged.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//




public class MediumDamaged extends DamageDecorator {
	public static int threshold;
	
	public MediumDamaged(RoboFighter f) {
		super(f);
	}
	
	@Override
	public void draw(Graphics2D g2d) {
		g2d.setColor(new Color(220, 148, 22));
		
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
		g2d.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
		
		g2d.drawOval((int) x - radius + radius/4,(int) y - radius + radius/4, (int) 2*radius - 2*radius/4, (int) 2*radius- 2*radius/4);
		decoratedRoboFigher.draw(g2d);
	}
}
