
import javax.swing.JFrame;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SimulationRunner.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//


public class SimulationRunner extends Thread {
	public static Simulation simulation;
	public static Display display;
	
	public static void main(String[] args) {
		simulation = new Simulation();
		JFrame mainWindow = new JFrame();
		mainWindow.setTitle("War Zone: 443");
		mainWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		display = new Display(simulation);
		
		
		//display.add(simulation.legend);
		
		
		mainWindow.add(display);
		
		
		
		mainWindow.pack();
		mainWindow.setVisible(true);
		
		try {
			while(true) {
				simulation.step(0.2);
				display.repaint();
				simulation.legend.repaint();
				sleep(2);
			} 
		}
		catch (InterruptedException e) {
			e.printStackTrace();
		}
		catch (Exception e) {
			//e.printStackTrace();
		}
	}
}
