import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SRandom.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//




public class SRandom extends FightStrategy {
	Random random;
	
	public SRandom() {
		super();
		
		this.stepsToFire = 70;
		random = new Random();
	}
	
	@Override
	public void move(RoboFighter r, double deltaTime) {
		
		int randInt = random.nextInt();
		
		this.stepDeltaX = Math.cos(randInt);
		this.stepDeltaY = Math.sin(randInt);
		
		r.x += deltaTime*stepDeltaX;
		r.y += deltaTime*stepDeltaY;
		
		int insCheck;
		
		insCheck = insideCheck(r.x, r.y, r.simulation.legend.width, r.simulation.legend.height, -1*r.radius);
		
		if(insCheck == 1) {
			stepDeltaX *= -1;
			r.x += deltaTime*2*stepDeltaX;
		}
		if(insCheck == 2) {
			stepDeltaY *= -1;
			r.y += deltaTime*2*stepDeltaY;
		}
		
		insCheck = insideCheck(r.x, r.y, r.simulation.zoneWidth, r.simulation.zoneHeight, r.radius);
		
		if(insCheck == -1) {
			stepDeltaX *= -1;
			r.x += deltaTime*2*stepDeltaX;
		}
		if(insCheck == -2) {
			stepDeltaY *= -1;
			r.y += deltaTime*2*stepDeltaY;
		}
		
		avoidCollision(r.x, r.y, r);
			
		if((r.simulation.totalSteps % stepsToFire) == 0 && r.ammunition > 0) {
			
			double pStepDeltaX = Math.cos(randInt);
			double pStepDeltaY = Math.sin(randInt);
			
			r.simulation.projectiles.add(new Projectile(r.x + pStepDeltaX*(r.radius),
					r.y + pStepDeltaY*(r.radius), 
					pStepDeltaX, pStepDeltaY, r.color, r.simulation, r));
			
			r.ammunition--;
		}
		
		
	}
	
}
