//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SturdyFactory.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//




public class SturdyClutterFactory extends ClutterFactory {

	public static int radius;

	public SturdyClutterFactory(Simulation simulation) {
		super(simulation);
	}
	
	@Override
	public Clutter createClutter() {
		return new SturdyClutter(minStrength, maxStrength, simulation, radius);
	}
	
}
