import java.awt.Color;
import java.awt.Graphics2D;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SturdyClutter.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//




public class SturdyClutter extends Clutter {
	
	public SturdyClutter(int minStrength, int maxStrength, Simulation simulation, int radius) {
		super(radius, simulation);
		
		this.strength = simulation.randomGenerator.nextInt(maxStrength) + minStrength;
		this.color = Color.ORANGE;
		this.type = 1; // denoting sturdy clutter;
	}
	
	@Override
	public void draw(Graphics2D g2d) { 
		super.draw(g2d);
	}
}
