import java.awt.Color;
import java.awt.Graphics2D;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WeakClutter.java
//  @ Date : 3/29/2013
//  @ Author : 
//
//


public class WeakClutter extends Clutter {
	
	public WeakClutter(int minStrength, int maxStrength, Simulation simulation, int radius) {
		super(radius, simulation);
		
		this.strength = simulation.randomGenerator.nextInt(maxStrength) + minStrength;
		this.color = Color.CYAN;
		
		this.type = 0; // denoting weak clutter
	}
	
	@Override
	public void draw(Graphics2D g2d) { 
		super.draw(g2d);
	}
	
	
	
}
